name: Test
on: push
jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2
        - name: Install
          npm ci
        - name: Lint
          run: npm run lint
            